### ISSUE TITLE
WrongState format simplification

### ISSUE THREAD

**Issue by Hexlord** [louis-langholtz/PlayRho#123]
### Expected/Desired Behavior or Experience:
Easy to use <throw WrongState("reason")>

### Actual Behavior:
Have to manually look current function's name and write 
<throw WrongState("ClassName::FunctionName reason")>

### Steps to Reproduce the Actual Behavior:
Look [here](https://github.com/louis-langholtz/PlayRho/commit/0eabda908000abfae1e3f9f9415121304359efa3#diff-ca5d213e1247af145222eee6d762d73aR877) to see such cases

Solution is to use [__FUNCTION__](https://gcc.gnu.org/onlinedocs/gcc/Function-Names.html) macro inside WrongState defenition

[This](https://stackoverflow.com/a/28088811/8597205) solution uses FUNCTION but also provides CLASS name on compiletime.

**Comment by Hexlord** [comment]
See [Patch-4](https://github.com/louis-langholtz/PlayRho/compare/master...Hexlord:patch-4) for a possible solution

**Comment by louis-langholtz** [comment]
@Hexlord I like the suggestion. I'd sort of passed on doing this before since it requires the definition of a macro and I'd documented that PlayRho header files by default don't export any macros other than include guards.

StackOverflow has some [entries](https://stackoverflow.com/a/4384825/7410358) on this. There are standard language defined macros for this but I don't believe any will work the way we'd want from inside the constructor's code; they instead have to be used at the site of the `throw` statements. That's of course unfortunate since then there's no way linguistically to enforce the macro's use then which would be the coolest to me.

Given that the include files already export macros (their include guards) I don't see adding other kinds as really that different. They should just all be prefixed with the same `PLAYRHO_` to begin with so kind of keep them in their own namespace as far as the C pre-processor is concerned.

I assigned this issue to you since it's not something I'd want to tackle right now since I'm tied up with working on the `DynamicTree` code deeply at the moment.

**Comment by Hexlord** [comment]
@louis-langholtz I think I can provide run-time solution, i think it is ok as throw is a slow operation by itself. Will come up with a pull request.

**Comment by Hexlord** [comment]
This produces:

> WrongState exception at CTest::test(): World is locked

```
//clang 3.8.0
//g++  5.4.0

#include <iostream>
#include <string>
#include <stdexcept>

class WrongState: public std::logic_error
    {
    public:
        using std::logic_error::logic_error;
        
        explicit WrongState(const std::string& what_func, const std::string& what_arg) :
            logic_error("WrongState exception at " + std::string(what_func) + ": " + what_arg)
        {
            // Intentionally left empty
        }
    
        explicit WrongState(const std::string& what_func, const char* what_arg) :
            logic_error("WrongState exception at " + std::string(what_func) + ": " + what_arg)
        {
            // Intentionally left empty
        }
    
        static std::string UnprettifyFunc(const char* what_func_pretty, const char* what_func)
        {
            std::string result = what_func_pretty;
            std::string func = what_func;
            func += "(";
            int count = result.size();
            int start = result.find(func);
            while(true)
            {
                if(start < 1 || result[start-1] == ' ') break;
                --start;
            }
            
            return result.substr(start, count - start);
        }
    
        
    };

#define PLAYRHO_WRONG_STATE(message) do{throw WrongState(WrongState::UnprettifyFunc(__PRETTY_FUNCTION__, __FUNCTION__), message);}while(0);

class CTest
{
    public:
    static void test()
    {
        PLAYRHO_WRONG_STATE("World is locked");

    }
};

int main()
{
    try {
        CTest::test();
    } catch (WrongState& e)
    {
        std::cout << e.what();
    }
}

```

Should I now integrate this solution?

**Comment by louis-langholtz** [comment]
@Hexlord Thanks for looking into this.

I take it that this is something interesting to you then as it looks like you've put some time into it. If so, what seems to be the prevailing rimes and reasons related to constructing exception messages? I ask because I'm indeed wondering about that. I figure the clear reasons for particular ways to use exceptions are in the [C++ Core Guidelines](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Re-throw) but I haven't found them providing any guidance around exception mechanisms or contents related to this.

Off the top of my head, here's concerns I have but that I'm admittedly interested in discussing...

**I'm reluctant to replace in-place `throw` keywords with any macro that wraps it.**

Here's some reasons for this reluctance:
- It hides (through a level of abstraction) that an exception is originating from that place in the code.
- It hides (again through the indirection of the abstraction) that control flow doesn't continue from that place in the code.

So I guess it's fair to say that I'm of the opinion that it's safer to avoid adding new non-returning functions/keywords. Adding the `[[noreturn]]` attribute should help for this but again that's on the function's declaration which isn't as clear as sticking with the already available standard keywords and functions that are recognized as non-returning. 

**I'm reluctant to embed `"WrongState exception at "` into the exception's `what` explanatory string.**

The `WrongState` exception is already a *wrong state* indicating object so adding that to its `what` explanatory string seems redundant and fragile in that sense.

**`__FUNCTION__` seems non-standard.**

From [GCC's page on Function Names as Strings](https://gcc.gnu.org/onlinedocs/gcc-4.7.3/gcc/Function-Names.html):

> The first of these is `__func__`, which is part of the C99 standard.

Also:

> `__FUNCTION__` is another name for `__func__`. Older versions of GCC recognize only this name. However, it is not standardized. For maximum portability, we recommend you use `__func__`, ...

**Comment by Hexlord** [comment]
> __FUNCTION__ seems non-standard.
> 
> From GCC's page on Function Names as Strings:
> 
> The first of these is __func__, which is part of the C99 standard.
> Also:
> 
> __FUNCTION__ is another name for __func__. Older versions of GCC recognize only this name. However, it is not standardized. For maximum portability, we recommend you use __func__, ...

That is the way when it works on both clang and gcc

> I'm reluctant to embed "WrongState exception at " into the exception's what explanatory string.
> 
> The WrongState exception is already a wrong state indicating object so adding that to its what explanatory string seems redundant and fragile in that sense.

Well I was inspired by Java, but whatever you like will do

> I'm reluctant to replace in-place throw keywords with any macro that wraps it.
> 
> Here's some reasons for this reluctance:
> 
> It hides (through a level of abstraction) that an exception is originating from that place in the code.
> It hides (again through the indirection of the abstraction) that control flow doesn't continue from that place in the code.
> So I guess it's fair to say that I'm of the opinion that it's safer to avoid adding new non-returning functions/keywords. Adding the [[noreturn]] attribute should help for this but again that's on the function's declaration which isn't as clear as sticking with the already available standard keywords and functions that are recognized as non-returning.

Then you can NOT obtain caller's function name in any way.
I would suggest renaming macro to playrho_throw, if it works with you.

**Comment by louis-langholtz** [comment]
How about something like the following?

    class CTest
    {
        public:
        static void test()
        {
            throw WrongState(std::string(__func__) + ": World is locked");
        }
    };

I agree it's not fancy, but it's simplicity has some appeal to me. Alternatively, maybe wrap some of that in a define like:

    #define PLAYRHO_EXCEPTION_MSG(a) (std::string(__func__) + std::string(": ") + (a)

What are your thoughts?

**Comment by Hexlord** [comment]
Well it does not display class name, yet if it is ok

`throw WrongState(PLAYRHO_EXCEPTION_MSG("World is locked"));`

seems legit, yet I would prefer PLAYRHO_THROW("World is locked") or smth (:

**Comment by louis-langholtz** [comment]
Just FYI... I'm still thinking about this.

I've been looking at [boost's exception](http://www.boost.org/doc/libs/1_65_1/libs/exception/doc/boost-exception.html) for insights. Have you seen it lately? In any case, in support of your preference for having a macro that invokes the `throw`, boost has its `BOOST_THROW_EXCEPTION` macro that does that too. It also adds the `__FILE__` and `__LINE__` info (though in a different way than we've been thinking of it).

An advantage I can appreciate to wrapping the `throw` keyword within a macro would be an ability to redefine the macro to use a different non-returning mechanism than C++ exceptions.

**Comment by louis-langholtz** [comment]
@Hexlord Sorry I haven't gotten back to you on this. The changes you're suggesting here aren't bad by any means. I'd like to keep this issue open and just keep it on hold for now though. Please don't take my hesitation on them as a sign of disapproval however.  If exceptions in PlayRho are a priority for you, go ahead and make one or more pull requests for code you'd prefer or provide more use cases or argument in support of changes you want and I'll consider it more.

If there are other things that are more interesting for you though in PlayRho, I'd like to encourage that in the meantime. The logo which I think you'd made some proposals for in the past is something I'm more keen on right now. I think you also had proposed some renaming of some classes, like to get more consistent with uses of class name suffices like `2D` vs. `2` (as in `Vector2D` vs. `Vec2` etc). I've opened issue #178 for this and would love your feedback there on that topic!

**Comment by Hexlord** [comment]
Screw macroses
