### ISSUE TITLE
VS2017 TestBed build problem

### ISSUE THREAD

**Issue by Hexlord** [louis-langholtz/PlayRho#228]
### Expected/Desired Behavior or Experience:
TestBed can be built out of the box via provided solution.

### Actual Behavior:
Couldn't find GLFW dependency header file.

### Steps to Reproduce the Actual Behavior:
Clone PlayRho and launch VS2017 solution, build TestBed with Release cfg.

**Comment by louis-langholtz** [comment]
Sorry about this not working and thank you for the report!

Just so that I'm clear, is this problem occurring for you using the [Windows CMake build instructions for the Testbed](https://github.com/louis-langholtz/PlayRho/tree/master/Testbed#windows-using-vs2017-and-cmake), or is it occurring only when trying to build the Testbed directly from the solution file?

If the problem is only in the latter situation, would it perhaps be best to get rid of the provided solution file and require the use of CMake (rather than continually trying to maintain the solution file in addition to the CMake files)? I'm tempted to do this since every different build path grows the maintenance problem faster than's practically scalable at least for me. Even adding the solution file to the AppVeyor CI systems is something I'm averse to given the length of time it takes just doing the CMake build matrix.

**Comment by Hexlord** [comment]
> directly from the solution file
Well the solution could be submodule dependency being added for GLFW/GLEW, so that starting to use PlayRho would be easier (clone & build), but it is okay as it is, just a little confusing, so I agree with the point of leaving CMake alone.

**Comment by louis-langholtz** [comment]
Updated the main INSTALL.md file to make it clearer to use CMake when building on Windows.
