### ISSUE TITLE
Cocos2d-x Vec2 same name in two namespace cocos2d and playrho

### ISSUE THREAD

**Issue by hangocanh2303** [louis-langholtz/PlayRho#239]
when i using this line: using namespace playrho; -> it can't be use in cocos2d-x because in namespace cocos2d have the same class Vec2
Next: how to debug draw in your engine ?

**Comment by louis-langholtz** [comment]
@hangocanh2303 Thank you for opening this issue! I've marked it with the "help wanted" label since I imagine others are likely to also wonder about this and/or have thoughts on it, and I'd like to encourage them to jump in with their perspectives as well if they'd like.

As I understand it, you're asking about two issues:

1. How to use PlayRho with the Cocos2d software framework; specifically regarding names that may exist in both.
2. How to visually debug what's going on in terms of the PlayRho bodies and their shapes.

For the **first issue**, this seems like a general issue that can come up when using multiple libraries. I think the most idiomatic solution is to avoid importing entire namespaces and instead prefix everything with their namespace names (or abbreviate them and use those abbreviations). The `Benchmark` application is coded that way and one will find `std` prefixing standard library things and `playrho` prefixing the PlayRho things.

Will that solve the name conflicts for you? Is there another solution you'd recommend over this?

Admittedly, writing out all the namespace prefixes I find encumbering which is why I effectively imported the whole `playrho` namespace into the Testbed and HelloWorld applications. I apologize if you followed my lead in this regard. I have been considering changing those applications to avoid establishing the problematic precedence.

For the **second issue**, you could follow the way the `Testbed` draws bodies and their PlayRho shapes. See code like [`ShapeDrawer`](https://github.com/louis-langholtz/PlayRho/blob/master/Testbed/Framework/Test.cpp#L49) for an example of this. The technique used in the `Testbed` is meant for drawing the underlying shape configurations however which isn't necessarily the best way to draw things. I mention this because one could alternatively draw other representations of the physically simulated properties like:

1. Axis aligned bounding boxes for those bodies or fixtures or shapes.
2. The convex hulls (the child shapes) which all shapes decompose to in terms of collision detection and handling.
3. The shapes users would actually see for which physics engines like PlayRho only do physical approximations of.

No one of these is definitely more correct. That'd be for you to decide for your use.

On a related note, Box2D has the `b2Draw` class and the `g_debugDraw` global in it with methods like `b2World::DrawShape` that works with these. I dislike these and see them as unnecessarily creating [tighter coupling](https://en.wikipedia.org/wiki/Coupling_(computer_programming)#Disadvantages). By contrast, PlayRho doesn't have these nor `b2Shape::Type Fixture::GetType()` and still achieves the same end goal of being able to display the shapes but with looser coupling.

I suspect this difference could be a gotcha though for people coming from a background of a physics engine like Box2D.

**Comment by hangocanh2303** [comment]
For solution 1: I write cocos2d::Vec2 or playrho::Vec2 to slove this. 
For solution 2: I see the Testbed folder. I will try it
Thank you for answer. Bellow is my day question :)) hope you help me.
1. I write code for online physic turn base game. But problem of box2d is: box2d is not the same result in all platform with same input. I want with the same input, result the same in all platform. 
Because of the problem of floating-point determinism across different devices. Your engine slove this problem ? with fixed point number, how two use it for your engine? 
2. with your engine, It seem only work with 64bit device ? I run this with 32bit device example iphone 5. Build failed with some error like: uint128_t does not name a type and more.

**Comment by louis-langholtz** [comment]
Thank you for continuing to ask questions. I appreciate that and find the questions helpful.

As it sounds like you're aware, floating point operations can get different results on some different platforms. Theoretically speaking, a fixed point library should be able to avoid differences between platforms. I don't believe the fixed point code that I whipped up for PlayRho avoids all differences however.

For functions like `sin` and `cos` the current PlayRho fixed point code falls back to using floating point support and then converts it back again to fixed point format. I believe there are some simple Taylor Series approximations which I could use to avoid this problem but I haven't spent the time to do that. A harder problem that would need to be solved is the need for 128-bit wide integer support across all platforms.

Perhaps a better direction would be to get PlayRho building with an external mathematics library providing a type that's designed to give the same results on all platforms. I'll be working on this more but that's not usable yet.

With respect to your question of whether PlayRho works on 32-bit devices, it can but it requires some knowledge of whether the platform supports the 128-bit integer types or not. Sounds like what you've run into. PlayRho is meant to be platform independent but is perhaps too aggressive at assuming 128-bit integer support. I've opened issue #241 to address this problem.
