### ISSUE TITLE
ApplyForce* waking up bodies.

### ISSUE THREAD

**Issue by ninnghazad** [louis-langholtz/PlayRho#246]
It looks like ApplyForce* has dropped the wake-parameter. Now it will still be a lot of code until i am again at the point where i can actually see the effects of this - but before transitioning to playrho i relied on that parameter for custom gravity. I have global gravity disabled and instead have entities that may attract and be attracted by others. That is used for spherical gravity around little planets. If entities lie upon the surface of such planet they need to be able to fall asleep despite the custom gravity (using ApplyForce*) being applied to them. They are, with respect to the surface they lie on, at rest.
The docs state that "Non-zero forces wakes up the body." - is what i want to do still possible? Am i missing something in my line of thinking here?

(Also shouldn't that be "force wakes up" in the docs? but non-native english so not sure)

**Comment by louis-langholtz** [comment]
That's an interesting use case. I have a Solar System Testbed demo that sounds similar.

In the category of possible Box2D to PlayRho gotchas, PlayRho doesn't automatically clear forces doing potentially unnecessary work like Box2D may do. So I suspect your code will behave better using `SetForce` instead of `ApplyForce`, where the latter really will accumulate the forces.

Eventually `Body::SetAcceleration` gets called in PlayRho. PlayRho persists the acceleration &mdash; instead of forces as Box2D does &mdash; which saves on recalculating the accelerations each step.

Currently the PlayRho code is setup so that setting any non-zero acceleration to a body will wake it up.

Thinking about this now, the current implemented behavior seems wrong. It should only wake up the body if the new acceleration is either greater in magnitude than the old, or in a different direction than the old. This should keep a sleeping body asleep even if its acceleration is being set every step (so long as the direction of the acceleration doesn't change nor the magnitude increase above what it was previously).

**Comment by ninnghazad** [comment]
Nice. Thanks!

**Comment by louis-langholtz** [comment]
Just merged in a slight change to the `Body::SetAcceleration` code (that everything calls down to) that does more to prevent waking up an asleep body. So now sleeping body should only awake if given a greater acceleration or one in a different direction. Hope this helps!

Please re-open this issue if this code still isn't doing the right thing. Thanks!
