### ISSUE TITLE
coveralls.io coverage reporting no longer working for new pull requests

### ISSUE THREAD

**Issue by louis-langholtz** [louis-langholtz/PlayRho#324]
Seems coveralls.io is no longer supporting use of the `lcov` tool as this project has used before. Their current recommended tool is to use [cpp-coveralls](https://github.com/eddyxu/cpp-coveralls).

I've been trying to switch to cpp-coveralls in [my pull request 322](https://github.com/louis-langholtz/PlayRho/pull/322) but that new setup isn't recognizing any code coverage.

I've filed [an issue at the cpp-coveralls github pages](https://github.com/eddyxu/cpp-coveralls/issues/137) hoping someone there will help. Alternatively, if anyone following this project can spot what the problem is, I'd love to get your help!

**Comment by ninnghazad** [comment]
Hey @louis-langholtz .
i forked PlayRho and played around with coveralls. using cpp-coveralls from the cli kinda worked, so did using it in .travis.yml.
[coveralls thingy](https://coveralls.io/builds/22354608)
but the coverage is kinda low - i remember it being much higher. is that what you mean by not working anymore?
oh, and at first coveralls wouldn't show me the sources, and asked me to specify a pre/post-fix for the paths, i set 'PlayRho' as a prefix and it showed the sources.

**Comment by louis-langholtz** [comment]
Thank you so much for helping with this!

Coverage used to be above 99% but then I haven't been able to get coveralls working for too long a time. So 86% looks bad but at least it looks like you got this working again. Awesome!!

It did use to cover headers too I believe but had been using the `lcov` suite of tools. Perhaps the two different coverage tool sets measure differently? Or perhaps in the interim while coverage wasn't being updated, I'd inadvertently merged some changes that lowered the coverage from 99% to the 86%?

**Comment by ninnghazad** [comment]
It seems the missing coverage is, except for CoreDumper.cpp, all in header files. However some headers look good, so i don't think it's a 'headers not working' thing.  looking at the individual reports of those files some of those covered/not-covered markers don't make a whole lot of sense to me. in Common/BoundedValue.hpp for example it marks a comment and other seemingly weird parts like half of a declaration and the like. The last changes to that file don't look like they are related to the pattern here. There are markers on CheckIfAboveNegInf, but a quick grep and run of UnitTests shows that part being tested, and cpp-coverage shows a bunch gcovs for that file.
So... i don't know =)
But 99 to 86% seems more like an error to me than you forgetting tests.
Maybe it's just my otherwise messy setup.
