### ISSUE TITLE
TypeInfo template does not work as expected in VS 2019 version 16.7.7

### ISSUE THREAD

**Issue by pigpigyyy** [louis-langholtz/PlayRho#370]
*The TypeInfo template does not work as expected in VS 2019 version 16.7.7*

### Expected/Desired Behavior or Experience:
For example, `&TypeInfo<DiskShapeConf>::name` and `&TypeInfo<PolygonShapeConf>::name` are expected to be different addresses. 

### Actual Behavior:
`&TypeInfo<DiskShapeConf>::name` and `&TypeInfo<PolygonShapeConf>::name` are sharing the same address when compiled in the new MSVC with release mode. 

### Steps to Reproduce the Actual Behavior:
```cpp
#include <iostream>

template <typename T>
struct TypeInfo
{
  static constexpr const char* name = nullptr;
};

int main()
{
  std::cout << reinterpret_cast<const void*>(&TypeInfo<double>::name) << '\n';
  std::cout << reinterpret_cast<const void*>(&TypeInfo<int>::name) << '\n';
  return 0;
}
```

**Comment by louis-langholtz** [comment]
Thanks for reporting this.

This is a strange situation. Godbolt seems to use different version numbers for it's MSVC compilers but [Godbolt suggests this works with the version used](https://godbolt.org/z/GsvYvd).

I'll be investigating this more.

**Comment by louis-langholtz** [comment]
@pigpigyyy Do you by chance have any other versions of VS2019 installed that you can reproduce this problem on or confirm that it works as intended on? I've been trying other versions of VS and haven't so far been able to reproduce this problem.

**Comment by louis-langholtz** [comment]
More data points from additional testing of mine:
- `TypeInfo` working as intended with VS2017 15.9.2 on x64.
- `TypeInfo` working as intended with VS2019 16.7.7 on x64.

So not sure why this isn't working correctly for @pigpigyyy .

**Comment by louis-langholtz** [comment]
Is anybody else seeing this problem? Can anybody reproduce it on Compiler Explorer / Godbolt?

**Comment by pigpigyyy** [comment]
Just made sure the MSVC is version 19.27.29112 on my machine, producing the same result for x64 and x86 release mode.

**Comment by pigpigyyy** [comment]
I'm pretty sure it is a bug in the MSVC version 19.27.29112, tried
```cpp
#include <iostream>

template <typename T>
struct TypeInfo
{
   static constexpr const char* name = nullptr;
};

int main()
{
   const bool a = (&TypeInfo<int>::name == &TypeInfo<double>::name);
   bool b = (&TypeInfo<int>::name == &TypeInfo<double>::name);
   std::cout << a << ' ' << b << '\n';
   return 0;
}
```
Got the output  `0 1`

**Comment by louis-langholtz** [comment]
Thank you for trying these other things out! Seems like you've come up with a viable strategy for improving the reliability of this `TypeInfo` mechanism. I'm relieved to learn of this!

What leads you to guess that this is a bug specific to MSVC version 19.27.29112? Certainly seems possible that this is a compiler bug. Wouldn't be the first I've seen. But does seem odd that it's not showing up on the version of MSVC 19.27 that I've tried on.

Does the unexpected behavior also happen without the use of the /GL flag? I'm curious if perhaps there's a different flag that you're using or not using which might also correspond to this problem like this /GL flag. I hadn't used it in my tests before. Godbolt results in a no code generated state with it that suggests perhaps that triggers a `static_assert` checking for correct behavior. I'll try on a local VS2019 setup in a little while.

As a side note, I see that `__FUNCSIG__` isn't standard C++ like say `__func__` (since C99) or `std::source_location::current().function_name()` (in C++20). I see that it's a Microsoft added macro not supported seemingly in gcc. I feel comfortable enough though with using the combination of macros available in code like:
```
template <typename T>
struct TypeInfo
{
    static constexpr const char* NameFunction()
    {
#if defined(_WIN32) 
        return __FUNCSIG__;
#elif defined(__GNUC__)
        return __PRETTY_FUNCTION__;
#else
        return __func__; // not unique but maybe still helpful at avoiding compiler issues
#endif
    }
    
    static constexpr const char* const name = NameFunction();
};
```

**Comment by louis-langholtz** [comment]
I've been able to reproduce this problem now by using the `/GL` flag (for whole program optimization) with VS2019 16.7.7 using the MSCV 14.27.29110 toolset. Guessing this may be more of an expected behavior of MSVC than a bug.
