### ISSUE TITLE
Wrong position for transformation

### ISSUE THREAD

**Issue by opera-aberglund** [louis-langholtz/PlayRho#560]
I'm testing this out now and I'm having a small issue with it. I removed the calls to `UseLocation` and `UseAngle` and replaced them with `UseSweep`. However, the resulting body doesn't have the same location, or "`m_xf`", as the one I serialized it from. It seems that the value of `m_xf` is set from the `pos0` from the sweep, done from the `GetTransformation` here:
```c++
Transformation GetTransformation(const BodyConf& conf) noexcept
{
    return {conf.sweep.pos0.linear, UnitVec::Get(conf.sweep.pos0.angular)};
}
```
when the value of `x_mf` in the old body is the value of `pos1` of the sweep. And I can't call `UseLocation` to fix this, because then I will loose the `pos0` from the sweep.

I also had to set `resetMassData` to false, because otherwise I will also loose the `pos0` from the sweep, but I guess I always have to avoid this function if I want an exact copy of a body?

_Originally posted by @opera-aberglund in https://github.com/louis-langholtz/PlayRho/issues/549#issuecomment-1864246363_

**Comment by louis-langholtz** [comment]
I've run into this problem before myself. But is this more of a wrong position, or more of a it-doesn't-work-as-expected problem?? I'm wondering this myself.

Even when I recently added the ability to set the sweep, I ran into this. Also, I ran into the gotcha of having to set `resetMassData` to false.

**Comment by opera-aberglund** [comment]
> But is this more of a wrong position, or more of a it-doesn't-work-as-expected problem??

I'm not sure either. I really have to emphasise that when I filed these issues I was almost completely blind to how things logically should work; I was solely looking at how I can recreate an exact copy of a serialized world, and I just found I had to change this function getting `pos0` to `pos1` for the equality to be true.

**Comment by opera-aberglund** [comment]
I'm fairly certain that changing it to `pos1` would be correct, because my game state gets desynchronized after serialization and deserialization if I just the current `pos0` in the function.

**Comment by louis-langholtz** [comment]
Some notes on this, at least for myself:
1. In commit a709055, [`playrho/d2/BodyConf.hpp`](https://github.com/louis-langholtz/PlayRho/commit/a7090552756bb03c40f42a1ed8b171fad6bd6c4e#diff-26c416999947d4351fc4f9dc8b1866eab7b30053511e6c60e437665e0875ce6e) was changed to add support for configuring with `Sweep` information, instead of `location` and `angle`.
2. This meant that then one variable (`sweep` and in particular `sweep.pos0`), spoke for what used to be two separate variables (`location`, and `angle`), and could then also convey that state for the other stage of the sweep (`sweep.pos1`).
3. This also meant that `Body::m_sweep` could then be initialized by `BodyConf::sweep`, instead of having `Body::m_sweep` initialized to the more limited `Sweep{Position{bd.location, bd.angle}}`.

**Comment by louis-langholtz** [comment]
I've merged in changes now to the master branch to address this. Closing this assuming that it does. Please let me know though either way. Thanks!
