### ISSUE TITLE
No equivalent "IsDestroyed" method in World interface

### ISSUE THREAD

**Issue by opera-aberglund** [louis-langholtz/PlayRho#561]
The "IsDestroyed" methods in `AabbTreeWorld` doesn't exist in the `World` interface. For example:
```c++
bool IsDestroyed(const AabbTreeWorld& world, BodyID id) noexcept
{
    return world.m_bodyBuffer.FindFree(to_underlying(id));
}
```

There should be something like:
```c++
bool IsDestroyed(const World& world, BodyID id)
{
    return world.m_impl->IsDestroyed_(id);
}
```
and equivalent in the `WorldConcept` and `WorldModel`...

**Comment by louis-langholtz** [comment]
Out of curiosity, what flavor of interface for this info would you prefer:

1. IsDestroyed(const World&, EntityID)
2. entity.IsDestroyed()
3. std::optional<Entity> GetEntity(const World&, EntityID)

**Comment by opera-aberglund** [comment]
> Out of curiosity, what flavor of interface for this info would you prefer:
> 
> 1. IsDestroyed(const World&, EntityID)
> 2. entity.IsDestroyed()
> 3. std::optional GetEntity(const World&, EntityID)

I would prefer 1 I think because it matches the signature of the `Destroy` function.

**Comment by louis-langholtz** [comment]
> I would prefer 1 I think because it matches the signature of the `Destroy` function.

Interesting to me that option 3 didn't get mentioned. Interesting in terms of discussion, because while I'm a fan of C++ _vocabulary_ types like `std::optional`, I'm also concerned about minimizing memory usage.

Specifically, making the underlying storage arrays that the implementing world uses be arrays of `std::optional<T>` instead of arrays of `T` seems more likely to be suboptimal bit-density wise than another possibility I'm thinking of.

In this case, PlayRho types like `Body` and `Contact` already provide boolean properties stored directly in bits packed optimally. That leads most naturally for me to options 1 and 2.

The more abstracted PlayRho types `Shape` and `Joint` don't seem to have as optimal, or, at least, not such a straight forward path for providing an is-destroyed piece of info. Perhaps the most straight forward to me is using their `has_value` member function for this. That way, supporting types (like `DiskShapeConf` for example), don't have to all change their interfaces to support this.

So I think that's what I'll do then, and why. I.e. provide interface 1 (and 2) for the PlayRho `Body`, `Contact`, `Joint`, `Shape` types. Assuming of course that this works out; I'm concerned I may yet encounter wrinkles with this design.

Relatedly from my thinking, and see issue #547, I'm continuing to consider removing all of the `World` based functions `GetBodies(const World&)`, `GetContacts(const World&)`, `GetJoints(const World&)` (and their implementation based counterparts).

**Comment by louis-langholtz** [comment]
The following is available now in current master branch:
- `IsDestroyed(const Body&)`.
- `IsDestroyed(const Contact&)`.
- `IsDestroyed(const Shape&)`.
- `IsDestroyed(const Joint&)`.
- `IsDestroyed(const World&, BodyID id)`.
- `IsDestroyed(const World&, ContactID id)`.

Relatedly, manifolds would use the info for contact.

I still have to add the following however - I'd forgotten these but meant to add these as well:
- `IsDestroyed(const World&, JointID id)`.
- `IsDestroyed(const World&, ShapeID id)`.

**Comment by louis-langholtz** [comment]
This is complete now with PR #566.
